language: objective-c

env:
  global:
  - AWS_DEFAULT_REGION=us-standard
  - AWS_ACCESS_KEY_ID=AKIAI2ERWDHLW3W24X3A
  - secure: "WSqA/RbX5O02CzjX2exYVNfIzgOotMYY+R8aooDTLVL0YePshZ/jj9SPELjCx6alp4xcUYEEPlqrdLznBN2yA/Lxjyjyd0DIHMubF4eiEgnwp9DO/29iLaikScIGKwvVq3yS0ThL4qPzrwQC91cG1EotY2SECFf6oWkmzcbT86g="

before_install:
- export PATH=$HOME/anaconda/bin:$PATH

script:
- python setup.py py2app fix bundle
- aws s3 cp dist/*dmg s3://mac.glueviz.org/

install:
- curl -OL http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.0.1-MacOSX-x86_64.sh
- chmod a+x ./Anaconda-2.0.1-MacOSX-x86_64.sh
- ./Anaconda-2.0.1-MacOSX-x86_64.sh -b -p $HOME/anaconda
- ./install_qt.sh
- which python
- which pip
- which macdeployqt
- pip install macholib==1.5.1 modulegraph==0.11 py2app==0.7
- pip install mock pyavm pytest requests plotly awscli==1.3.16
- git clone git://github.com/glue-viz/glue.git
- cd glue
- git checkout $TRAVIS_BRANCH
- python setup.py install
- cd ../
- conda list