language: objective-c

env:
  global:
  - TRAVIS_BRANCH=reorganize-widgets
  - AWS_DEFAULT_REGION=us-standard
  - AWS_ACCESS_KEY_ID=AKIAJ5PSFCJQOVO5QX3Q
  - secure: hIsaYsEzt/POKK8phOgIhQjYqIF+QaIy7uKyyunZGz4yk7evSLAH+43N1ekL0i4juf7/QtIiLi8t6mRArNHHCxvZI3I3FpqE1Q7JQX6ozbZ0z6udSu1YUJezZZgb6lImUotjIfndrmiJkW1Z/1H9raW/d52QaaspBNfUjAfwfg8=

before_install:
- export PATH=$HOME/anaconda/bin:$PATH

script:
  - echo "hello" > test_aws.txt
  - aws s3 cp test_aws.txt s3://glue-astrofrog/

install:
  - curl -OL http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.0.1-MacOSX-x86_64.sh
  - chmod a+x ./Anaconda-2.0.1-MacOSX-x86_64.sh
  - ./Anaconda-2.0.1-MacOSX-x86_64.sh -b -p $HOME/anaconda
  - pip install awscli==1.3.16

# script:
# - python setup.py py2app fix bundle
# - aws s3 cp dist/*dmg s3://mac.glueviz.org/
#
# install:
# - curl -OL http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.0.1-MacOSX-x86_64.sh
# - chmod a+x ./Anaconda-2.0.1-MacOSX-x86_64.sh
# - ./Anaconda-2.0.1-MacOSX-x86_64.sh -b -p $HOME/anaconda
# - ./install_qt.sh
# - which python
# - which pip
# - which macdeployqt
# - conda install --yes pyside
# - pip install macholib==1.5.1 modulegraph==0.11 py2app==0.7
# - pip install mock pyavm pytest requests plotly awscli==1.3.16 astrodendro
# - git clone git://github.com/astrofrog/glue.git
# - cd glue
# - git checkout $TRAVIS_BRANCH
# - python setup.py install
# - cd ../
# - conda list