language: objective-c

install:
   - brew update
   - brew install python
   - export PATH=/user/loca/bin:$PATH
   - export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
   - which python
   - echo $PYTHONPATH
   - brew install --verbose pyqt

script: /usr/local/bin/python test.py
