language: objective-c

env:
  global:
  - TRAVIS_BRANCH=tests-in-app
  - AWS_DEFAULT_REGION=us-standard
  - AWS_ACCESS_KEY_ID=AKIAJ5PSFCJQOVO5QX3Q
  - secure: hIsaYsEzt/POKK8phOgIhQjYqIF+QaIy7uKyyunZGz4yk7evSLAH+43N1ekL0i4juf7/QtIiLi8t6mRArNHHCxvZI3I3FpqE1Q7JQX6ozbZ0z6udSu1YUJezZZgb6lImUotjIfndrmiJkW1Z/1H9raW/d52QaaspBNfUjAfwfg8=

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/Users/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes pip numpy scipy matplotlib pandas astropy pygments pyzmq ipython scikit-image h5py py requests pytz mock requests pytest pyside
  - pip install macholib==1.5.1 modulegraph==0.11 py2app==0.7
  - pip install pyavm plotly awscli==1.3.16 astrodendro
  - git clone git://github.com/astrofrog/glue.git
  - cd glue
  - git checkout $TRAVIS_BRANCH
  - python setup.py install
  - cd ../
  - conda list

script:
- python setup.py py2app fix bundle
- aws s3 cp dist/*dmg s3://glue-astrofrog/
