language: objective-c

install:
   - curl -OL http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-1.5.1-MacOSX-x86_64.sh
   - chmod a+x ./Anaconda-1.5.1-MacOSX-x86_64.sh
   - ./Anaconda-1.5.1-MacOSX-x86_64.sh -b -p $HOME/anaconda
   - git submodule init
   - git submodule update
   - cd glue-qt
   - $HOME/anaconda/bin/python setup.py install
   - cd ..
   - $HOME/anaconda/bin/pip install py2app mock pyavm
   - $HOME/anaconda/bin/glue-deps list

script: $HOME/anaconda/bin/py.test glue-qt/glue/
